### ISSUE TITLE
The Bot crashes When Misconfigured with IRC Bridging

### ISSUE THREAD

**Issue by Ragora** [Ragora/PyIRCBot#9]
When configured to connect to some IRC channel and the discord bot isn't made aware of how to bridge it, crashes can occur:

May 06 18:43:54 ircd-server python3[8269]: future: <Task finished coro=<process_input_messages() done, defined at discordbridge/discordbridge.py:153> exception=KeyError('bottest',)>
May 06 18:43:54 ircd-server python3[8269]: Traceback (most recent call last):
May 06 18:43:54 ircd-server python3[8269]: File "/usr/lib/python3.4/asyncio/tasks.py", line 237, in _step
May 06 18:43:54 ircd-server python3[8269]: result = next(coro)
May 06 18:43:54 ircd-server python3[8269]: File "discordbridge/discordbridge.py", line 177, in process_input_messages
May 06 18:43:54 ircd-server python3[8269]: if channel.name in self.irc_to_discord[irc_channel] or int(channel.id) in self.irc_to_discord[irc_channel]:
May 06 18:43:54 ircd-server python3[8269]: KeyError: 'bottest'

**Comment by Ragora** [comment]
Handled via no-oping when the unbridged channel is encountered. Other addons can be configured to operate in different  channels this way.
